[package]
name = "bad-editor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description = "A small cross-platform modal terminal editor"

[[bin]]
name = "bed"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
bed-core.workspace = true
bed-terminal.workspace = true
bed-tui.workspace = true
