[package]
name = "bed-terminal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description = "Native terminal input, output, and mode handling for bed"

[dependencies]
anyhow.workspace = true
bed-vt100.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
