[package]
name = "bed-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description = "Editing, document, buffer, view, and history primitives for bed"

[dependencies]
anyhow.workspace = true
bed-file.workspace = true
unicode-segmentation.workspace = true
